service_name: "validator"

Postgres:
  # host: "127.0.0.1"
  host: "postgres"
  # port: "6132"
  port: "5432"
  user: "postgres"
  password: "password"
  DBName: "users"
  sslMode: "allow"

Server: #http
  host: "0.0.0.0"
  port: "3000"

Secret: "test-secret"
