service_name: "validator"

Postgres:
  host: "127.0.0.1"
  port: "6132"
  user: "postgres"
  password: "password"
  DBName: "users"
  sslMode: "allow"

Server: #http
  host: "0.0.0.0"
  port: "3000"

