service_name: "validator"

Postgres:
  host: "127.0.0.1"
  port: "8000"
  user: "postgres"
  password: "asdl.Fashydrh"
  DBName: "validator"
  sslMode: "allow"

grpc:
  client:
    host: "0.0.0.0"
    port: "3000"

Server: #http
  host: "0.0.0.0"
  port: "9090"

